### ISSUE TITLE
Populate Charm Store vcs-revisions Field

### ISSUE THREAD

**Issue by dshcherb** [openstack-charmers/release-tools#26]
Having repo-info is a nice way to preserve commit hash information (https://github.com/openstack-charmers/release-tools/blob/3f6a0cd2d31d95a0992ff28c904f5dbab8ab53ae/push-and-release#L109-L111), however, there is another place where we could add this metadata.

When 'charm push' is invoked, it tries to obtain commit information based on vcs-specific dot files in the current directory. For classic charms this seems to happen automatically as they are not pre-processed, for reactive this is not the case as they are built into a separate directory that does not contain a dot-file.

https://git.io/vxPvs

Example:
charm show cs:keystone --all
```
...
extra-info:
  vcs-revisions:
  - authors:
    - email: corey.bryant@c@nonical.com
      name: Corey Bryant
    commit: 3a4faf4df4794b6031b49079b2c56309a3578a7f
    date: 2018-03-12T14:15:26-04:00
    message: |-
      Update SSL/https documentation
...
      Change-Id: I2e0140f909ef2c57182895f37cf191b6bc80157b
      Closes-Bug: #1754682
      (cherry picked from commit 3384ddcb87a2c7621719c8844cf5a24a25936d48)
```
